businessLogic::FilterSearch
java.util.Calendar businessLogic.FilterSearch.cal
Referenced by businessLogic.FilterSearch.filterOfferByNights.
int businessLogic.FilterSearch.getMaxPrice(Vector< RuralHouse > list)
Referenced by gui.QueryAvailabilityClientAdvacedGUI.jbInit.
int businessLogic.FilterSearch.getMinPrice(Vector< RuralHouse > list)
Vector<Offer> businessLogic.FilterSearch.filterOfferByPrice(Vector< Offer > list, int maxPrice)
Referenced by gui.QueryAvailabilityClientAdvacedGUI.jbInit.
Vector<Offer> businessLogic.FilterSearch.filterOfferByRh(RuralHouse rh, Vector< Offer > list)
References domain.RuralHouse.getHouseNumber.
Referenced by gui.QueryAvailabilityClientAdvacedGUI.jbInit.
Vector<RuralHouse> businessLogic.FilterSearch.filterByCity(String city, Vector< RuralHouse > list)
Referenced by gui.QueryAvailabilityClientAdvacedGUI.jbInit.
Vector<Offer> businessLogic.FilterSearch.filterOfferByCity(String city, Vector< Offer > list)
Referenced by gui.QueryAvailabilityClientAdvacedGUI.jbInit.
Vector<Offer> businessLogic.FilterSearch.filterOfferByFirstDay(Date firstDay, Vector< Offer > list)
Referenced by gui.QueryAvailabilityClientAdvacedGUI.jbInit.
Vector<Offer> businessLogic.FilterSearch.filterOfferByLastDay(Date lastDay, Vector< Offer > list)
Referenced by gui.QueryAvailabilityClientAdvacedGUI.jbInit.
Vector<String> businessLogic.FilterSearch.getAllCity(Vector< RuralHouse > list)
Referenced by gui.QueryAvailabilityClientAdvacedGUI.jbInit.
Vector<Offer> businessLogic.FilterSearch.filterOfferByNights(String s, Vector< RuralHouse > list)
References businessLogic.FilterSearch.cal, domain.Offer.getFirstDay, domain.RuralHouse.getHouseNumber, domain.Offer.getLastDay, domain.Offer.getRuralHouse, domain.Offer.isBooked.
Referenced by gui.QueryAvailabilityClientAdvacedGUI.jbInit.