domain::Offer
Integer domain.Offer.offerNumber
Referenced by domain.Offer.getOfferNumber, domain.Offer.toString, domain.Offer.toString2.
Date domain.Offer.firstDay
Referenced by domain.Offer.getFirstDay, domain.Offer.Offer, domain.Offer.setFirstDay, domain.Offer.toString, domain.Offer.toString2.
Date domain.Offer.lastDay
Referenced by domain.Offer.getLastDay, domain.Offer.Offer, domain.Offer.setLastDay, domain.Offer.toString, domain.Offer.toString2.
float domain.Offer.price
Referenced by domain.Offer.getPrice, domain.Offer.Offer, domain.Offer.setPrice, domain.Offer.toString, domain.Offer.toString2.
RuralHouse domain.Offer.ruralHouse
Referenced by domain.Offer.getRuralHouse, domain.Offer.Offer, domain.Offer.setRuralHouse, domain.Offer.toString.
Reserva domain.Offer.reservaActual
Referenced by domain.Offer.getReserva, domain.Offer.removeReserva.
boolean domain.Offer.booked
Referenced by domain.Offer.isBooked, domain.Offer.Offer, domain.Offer.removeReserva, domain.Offer.setReserva.
domain.Offer.Offer()
domain.Offer.Offer(Date firstDay, Date lastDay, float price, RuralHouse ruralHouse, boolean booked)
References domain.Offer.booked, domain.Offer.firstDay, domain.Offer.lastDay, domain.Offer.price, domain.Offer.ruralHouse.
boolean domain.Offer.isBooked()
References domain.Offer.booked.
Referenced by businessLogic.FilterSearch.filterOfferByNights.
void domain.Offer.setReserva(Reserva r)
References domain.Offer.booked.
Reserva domain.Offer.getReserva()
References domain.Offer.reservaActual.
void domain.Offer.removeReserva()
References domain.Offer.booked, domain.Offer.reservaActual.
Referenced by dataAccess.DataAccess.removeReserva.
RuralHouse domain.Offer.getRuralHouse()
Get the house number of the offer.
the house number
References domain.Offer.ruralHouse.
Referenced by gui.FeedBackGUI.FeedBackGUI, businessLogic.FilterSearch.filterOfferByNights, gui.QueryAvailabilityClientAdvacedGUI.jbInit, gui.MisReservasGUI.MisReservasGUI, domain.ReservaOfferRhOwnerContainer.ReservaOfferRhOwnerContainer, domain.Reserva.toString2.
void domain.Offer.setRuralHouse(RuralHouse ruralHouse)
Set the house number to a offer.
house number
References domain.Offer.ruralHouse.
int domain.Offer.getOfferNumber()
Get the offer number.
offer number
References domain.Offer.offerNumber.
Referenced by dataAccess.DataAccess.createReserva, gui.QueryAvailabilityGUI.jButton1_actionPerformed.
Date domain.Offer.getFirstDay()
Get the first day of the offer.
the first day
References domain.Offer.firstDay.
Referenced by businessLogic.FilterSearch.filterOfferByNights, domain.RuralHouse.getOffers, gui.QueryAvailabilityGUI.jButton1_actionPerformed, domain.RuralHouse.overlapsWith, domain.Reserva.toString2.
void domain.Offer.setFirstDay(Date firstDay)
Set the first day of the offer.
firstDay The first day
References domain.Offer.firstDay.
Date domain.Offer.getLastDay()
Get the last day of the offer.
the last day
References domain.Offer.lastDay.
Referenced by businessLogic.FilterSearch.filterOfferByNights, domain.RuralHouse.getOffers, gui.QueryAvailabilityGUI.jButton1_actionPerformed, domain.RuralHouse.overlapsWith, domain.Reserva.toString2.
void domain.Offer.setLastDay(Date lastDay)
Set the last day of the offer.
lastDay The last day
References domain.Offer.lastDay.
float domain.Offer.getPrice()
Get the price.
price
References domain.Offer.price.
Referenced by gui.QueryAvailabilityGUI.jButton1_actionPerformed.
void domain.Offer.setPrice(float price)
Set the price.
price
References domain.Offer.price.
String domain.Offer.toString()
References domain.Offer.firstDay, domain.Offer.lastDay, domain.Offer.offerNumber, domain.Offer.price, domain.Offer.ruralHouse.
Referenced by gui.QueryAvailabilityGUI.jButton1_actionPerformed.
String domain.Offer.toString2()
References domain.Offer.firstDay, domain.Offer.lastDay, domain.Offer.offerNumber, domain.Offer.price.