configuration::ConfigXML
String configuration.ConfigXML.businessLogicNode
Referenced by configuration.ConfigXML.ConfigXML, configuration.ConfigXML.getBusinessLogicNode.
String configuration.ConfigXML.businessLogicPort
Referenced by configuration.ConfigXML.ConfigXML, configuration.ConfigXML.getBusinessLogicPort.
String configuration.ConfigXML.businessLogicName
Referenced by configuration.ConfigXML.ConfigXML, configuration.ConfigXML.getBusinessLogicName.
String configuration.ConfigXML.dataBaseOpenMode
Referenced by configuration.ConfigXML.ConfigXML, configuration.ConfigXML.getDataBaseOpenMode.
boolean configuration.ConfigXML.businessLogicLocal
Referenced by configuration.ConfigXML.ConfigXML, configuration.ConfigXML.isBusinessLogicLocal.
boolean configuration.ConfigXML.databaseLocal
Referenced by configuration.ConfigXML.ConfigXML, configuration.ConfigXML.isDatabaseLocal.
String configuration.ConfigXML.databaseNode
Referenced by configuration.ConfigXML.ConfigXML, configuration.ConfigXML.getDatabaseNode.
int configuration.ConfigXML.databasePort
Referenced by configuration.ConfigXML.ConfigXML, configuration.ConfigXML.getDatabasePort.
String configuration.ConfigXML.user
Referenced by configuration.ConfigXML.ConfigXML, configuration.ConfigXML.getUser.
String configuration.ConfigXML.password
Referenced by configuration.ConfigXML.ConfigXML, configuration.ConfigXML.getPassword.
String configuration.ConfigXML.locale
Referenced by configuration.ConfigXML.ConfigXML, configuration.ConfigXML.getLocale.
String configuration.ConfigXML.dbFilename
Referenced by configuration.ConfigXML.ConfigXML, configuration.ConfigXML.getDbFilename.
ConfigXML configuration.ConfigXML.theInstance
Referenced by configuration.ConfigXML.getInstance.
String configuration.ConfigXML.getLocale()
References configuration.ConfigXML.locale.
Referenced by gui.ApplicationLauncher.main.
int configuration.ConfigXML.getDatabasePort()
References configuration.ConfigXML.databasePort.
Referenced by businessLogic.BusinessLogicServer.BusinessLogicServer, dataAccess.DataAccess.DataAccess, dataAccess.ObjectdbManagerServer.ObjectdbManagerServer.
String configuration.ConfigXML.getUser()
References configuration.ConfigXML.user.
Referenced by dataAccess.DataAccess.DataAccess, dataAccess.ObjectdbManagerServer.ObjectdbManagerServer.
String configuration.ConfigXML.getPassword()
References configuration.ConfigXML.password.
Referenced by dataAccess.DataAccess.DataAccess, dataAccess.DataAccess.updateClient.
boolean configuration.ConfigXML.isDatabaseLocal()
References configuration.ConfigXML.databaseLocal.
Referenced by businessLogic.BusinessLogicServer.BusinessLogicServer, dataAccess.DataAccess.DataAccess, dataAccess.ObjectdbManagerServer.ObjectdbManagerServer.
boolean configuration.ConfigXML.isBusinessLogicLocal()
References configuration.ConfigXML.businessLogicLocal.
Referenced by businessLogic.BusinessLogicServer.BusinessLogicServer, gui.ApplicationLauncher.main.
String configuration.ConfigXML.getBusinessLogicNode()
References configuration.ConfigXML.businessLogicNode.
Referenced by businessLogic.BusinessLogicServer.BusinessLogicServer, gui.ApplicationLauncher.main.
String configuration.ConfigXML.getBusinessLogicPort()
References configuration.ConfigXML.businessLogicPort.
Referenced by businessLogic.BusinessLogicServer.BusinessLogicServer, gui.ApplicationLauncher.main.
String configuration.ConfigXML.getBusinessLogicName()
References configuration.ConfigXML.businessLogicName.
Referenced by businessLogic.BusinessLogicServer.BusinessLogicServer, gui.ApplicationLauncher.main.
String configuration.ConfigXML.getDbFilename()
References configuration.ConfigXML.dbFilename.
Referenced by dataAccess.DataAccess.DataAccess.
String configuration.ConfigXML.getDataBaseOpenMode()
References configuration.ConfigXML.dataBaseOpenMode.
String configuration.ConfigXML.getDatabaseNode()
References configuration.ConfigXML.databaseNode.
Referenced by businessLogic.BusinessLogicServer.BusinessLogicServer, dataAccess.DataAccess.DataAccess.
configuration.ConfigXML.ConfigXML()
References configuration.ConfigXML.businessLogicLocal, configuration.ConfigXML.businessLogicName, configuration.ConfigXML.businessLogicNode, configuration.ConfigXML.businessLogicPort, configuration.ConfigXML.databaseLocal, configuration.ConfigXML.databaseNode, configuration.ConfigXML.dataBaseOpenMode, configuration.ConfigXML.databasePort, configuration.ConfigXML.dbFilename, configuration.ConfigXML.getTagValue, configuration.ConfigXML.locale, configuration.ConfigXML.password, configuration.ConfigXML.user.
static String configuration.ConfigXML.getTagValue(String sTag, Element eElement)
Referenced by configuration.ConfigXML.ConfigXML.
static ConfigXML configuration.ConfigXML.getInstance()
References configuration.ConfigXML.theInstance.
Referenced by businessLogic.BusinessLogicServer.BusinessLogicServer, dataAccess.DataAccess.DataAccess, gui.ApplicationLauncher.main, dataAccess.ObjectdbManagerServer.ObjectdbManagerServer.