domain::Client
String domain.Client.userName
Referenced by domain.Client.Client, domain.Client.getUserName, domain.Client.setUserName.
String domain.Client.password
Referenced by domain.Client.Client, domain.Client.getPassword, domain.Client.setPassword.
String domain.Client.telegramId
Referenced by domain.Client.Client, domain.Client.getTelegramId, domain.Client.setTelegramId.
String domain.Client.cuentaBancaria
Referenced by domain.Client.Client, domain.Client.getCuentaBancaria, domain.Client.setCuentaBancaria.
String domain.Client.email
Referenced by domain.Client.Client, domain.Client.getEmail, domain.Client.setEmail.
Vector<Reserva> domain.Client.listaReserva
Referenced by domain.Client.addReserva, domain.Client.Client, domain.Client.getListaReserva, domain.Client.removeReserva.
int domain.Client.validationNumber
Referenced by domain.Client.Client, domain.Client.getValidationNumber, domain.Client.setValidationNumber.
boolean domain.Client.validated
Referenced by domain.Client.Client, domain.Client.isValidated, domain.Client.setValidated.
boolean domain.Client.sendBookByEmail
Referenced by domain.Client.Client, domain.Client.isSendBookByEmail, domain.Client.setSendBookByEmail.
boolean domain.Client.sendBookByTelegram
Referenced by domain.Client.Client, domain.Client.isSendBookByTelegram, domain.Client.setSendBookByTelegram.
domain.Client.Client()
domain.Client.Client(String userName, String password, String telegramId, String cuentaBancaria, String email)
References domain.Client.cuentaBancaria, domain.Client.email, businessLogic.GenerateValidationCode.getValidationNumber, domain.Client.listaReserva, domain.Client.password, domain.Client.sendBookByEmail, domain.Client.sendBookByTelegram, domain.Client.telegramId, domain.Client.userName, domain.Client.validated, domain.Client.validationNumber.
boolean domain.Client.isValidated()
References domain.Client.validated.
Referenced by gui.LoginGUI.LoginGUI.
boolean domain.Client.isSendBookByEmail()
References domain.Client.sendBookByEmail.
Referenced by gui.QueryAvailabilityClientAdvacedGUI.jButton1_actionPerformed, gui.ModifyAccountGUI.ModifyAccountGUI, gui.ModifyAccountGUI.updateTxtFields.
void domain.Client.setSendBookByEmail(boolean sendBookByEmail)
References domain.Client.sendBookByEmail.
Referenced by gui.ModifyAccountGUI.ModifyAccountGUI, dataAccess.DataAccess.updateClient.
boolean domain.Client.isSendBookByTelegram()
References domain.Client.sendBookByTelegram.
Referenced by gui.QueryAvailabilityClientAdvacedGUI.jButton1_actionPerformed, gui.ModifyAccountGUI.ModifyAccountGUI, gui.ModifyAccountGUI.updateTxtFields.
void domain.Client.setSendBookByTelegram(boolean sendBookByTelegram)
References domain.Client.sendBookByTelegram.
Referenced by gui.ModifyAccountGUI.ModifyAccountGUI, dataAccess.DataAccess.updateClient.
void domain.Client.setValidated(boolean validated)
References domain.Client.validated.
Referenced by dataAccess.DataAccess.updateClinetValidation.
int domain.Client.getValidationNumber()
References domain.Client.validationNumber.
Referenced by gui.ValidationGUI.ValidationGUI.
void domain.Client.setValidationNumber(int validationNumber)
References domain.Client.validationNumber.
void domain.Client.addReserva(Reserva r)
References domain.Client.listaReserva.
void domain.Client.removeReserva(Reserva r)
References domain.Client.listaReserva.
Vector<Reserva> domain.Client.getListaReserva()
References domain.Client.listaReserva.
Referenced by businessLogic.FacadeImplementationWS.getListReservaOfferRhOwnerContainer.
String domain.Client.getEmail()
References domain.Client.email.
Referenced by gui.QueryAvailabilityClientAdvacedGUI.jButton1_actionPerformed, gui.ModifyAccountGUI.ModifyAccountGUI, gui.ModifyAccountGUI.updateTxtFields, gui.ValidationGUI.ValidationGUI.
void domain.Client.setEmail(String email)
References domain.Client.email.
Referenced by gui.ModifyAccountGUI.ModifyAccountGUI, dataAccess.DataAccess.updateClient.
String domain.Client.getTelegramId()
References domain.Client.telegramId.
Referenced by gui.ModifyAccountGUI.ModifyAccountGUI, businessLogic.SendBooking.sendBookToTelegram, gui.ModifyAccountGUI.updateTxtFields, gui.ValidationGUI.ValidationGUI.
void domain.Client.setTelegramId(String telegramId)
References domain.Client.telegramId.
Referenced by gui.ModifyAccountGUI.ModifyAccountGUI, dataAccess.DataAccess.updateClient.
String domain.Client.getCuentaBancaria()
References domain.Client.cuentaBancaria.
Referenced by gui.ModifyAccountGUI.ModifyAccountGUI, gui.ModifyAccountGUI.updateTxtFields.
void domain.Client.setCuentaBancaria(String cuentaBancaria)
References domain.Client.cuentaBancaria.
Referenced by gui.ModifyAccountGUI.ModifyAccountGUI, dataAccess.DataAccess.updateClient.
String domain.Client.getUserName()
References domain.Client.userName.
Referenced by dataAccess.DataAccess.createReserva, businessLogic.FacadeImplementationWS.getListReservaOfferRhOwnerContainer, gui.QueryAvailabilityClientAdvacedGUI.jButton1_actionPerformed, gui.MisReservasGUI.MisReservasGUI, gui.ModifyAccountGUI.ModifyAccountGUI, gui.ModifyAccountGUI.updateTxtFields, gui.ValidationGUI.ValidationGUI.
void domain.Client.setUserName(String userName)
References domain.Client.userName.
String domain.Client.getPassword()
References domain.Client.password.
Referenced by businessLogic.Login.doLogin, gui.ModifyAccountGUI.ModifyAccountGUI, gui.ModifyAccountGUI.updateTxtFields.
void domain.Client.setPassword(String password)
References domain.Client.password.
Referenced by gui.ModifyAccountGUI.ModifyAccountGUI, dataAccess.DataAccess.updateClient.
String domain.Client.toString()
Referenced by dataAccess.DataAccess.createClient, dataAccess.DataAccess.getClientByUsername.