domain::ReservaOfferRhOwnerContainer
Reserva domain.ReservaOfferRhOwnerContainer.reserva
Offer domain.ReservaOfferRhOwnerContainer.offer
RuralHouse domain.ReservaOfferRhOwnerContainer.rh
Owner domain.ReservaOfferRhOwnerContainer.owner
domain.ReservaOfferRhOwnerContainer.ReservaOfferRhOwnerContainer(Reserva r)
References domain.Reserva.getOffer, domain.RuralHouse.getOwner, domain.Offer.getRuralHouse.
domain.ReservaOfferRhOwnerContainer.ReservaOfferRhOwnerContainer()
Reserva domain.ReservaOfferRhOwnerContainer.getReserva()
Referenced by gui.QueryAvailabilityClientAdvacedGUI.jButton1_actionPerformed, gui.MisReservasGUI.MisReservasGUI.
void domain.ReservaOfferRhOwnerContainer.setReserva(Reserva reserva)
Offer domain.ReservaOfferRhOwnerContainer.getOffer()
Referenced by gui.MisReservasGUI.MisReservasGUI.
void domain.ReservaOfferRhOwnerContainer.setOffer(Offer offer)
RuralHouse domain.ReservaOfferRhOwnerContainer.getRh()
void domain.ReservaOfferRhOwnerContainer.setRh(RuralHouse rh)
Owner domain.ReservaOfferRhOwnerContainer.getOwner()
Referenced by gui.QueryAvailabilityClientAdvacedGUI.jButton1_actionPerformed.
void domain.ReservaOfferRhOwnerContainer.setOwner(Owner owner)
String domain.ReservaOfferRhOwnerContainer.toString()
String domain.ReservaOfferRhOwnerContainer.toStringOfferRh()