gui::MainGUI
final long gui.MainGUI.serialVersionUID
ApplicationFacadeInterfaceWS gui.MainGUI.facade
Referenced by gui.MainGUI.getBusinessLogic, gui.MainGUI.getMainOwner, gui.MainGUI.MainGUI, gui.MainGUI.setBussinessLogic.
JPanel gui.MainGUI.jContentPane
Referenced by gui.MainGUI.getJContentPane.
JButton gui.MainGUI.boton1
JButton gui.MainGUI.boton3
Referenced by gui.MainGUI.getBoton3, gui.MainGUI.redibujar.
JRadioButton gui.MainGUI.rdbtnNewRadioButton
Referenced by gui.MainGUI.getRdbtnNewRadioButton.
JRadioButton gui.MainGUI.rdbtnNewRadioButton_1
Referenced by gui.MainGUI.getRdbtnNewRadioButton_1.
JRadioButton gui.MainGUI.rdbtnNewRadioButton_2
Referenced by gui.MainGUI.getRdbtnNewRadioButton_2.
JPanel gui.MainGUI.panel
Referenced by gui.MainGUI.getPanel.
final ButtonGroup gui.MainGUI.buttonGroup
Referenced by gui.MainGUI.getRdbtnNewRadioButton, gui.MainGUI.getRdbtnNewRadioButton_1, gui.MainGUI.getRdbtnNewRadioButton_2.
JLabel gui.MainGUI.lblLogedInAs
Referenced by gui.MainGUI.getLblLogedInAs.
JLabel gui.MainGUI.lblNewLabel
Referenced by gui.MainGUI.getLblNewLabel, gui.ApplicationLauncher.main, gui.MainGUI.redibujar.
JLabel gui.MainGUI.lblType
Referenced by gui.MainGUI.getLblType.
Owner gui.MainGUI.owner
Referenced by gui.MainGUI.getMainOwner, gui.LoginGUI.LoginGUI, gui.ModifyAccountGUI.ModifyAccountGUI, gui.OwnerGUI.OwnerGUI, gui.ModifyAccountGUI.updateTxtFields.
Client gui.MainGUI.client
Referenced by gui.ClientMainGUI.getBtnLogOut, gui.QueryAvailabilityClientAdvacedGUI.jButton1_actionPerformed, gui.LoginGUI.LoginGUI, gui.MisReservasGUI.MisReservasGUI, gui.ModifyAccountGUI.ModifyAccountGUI, gui.ModifyAccountGUI.updateTxtFields.
static ApplicationFacadeInterfaceWS gui.MainGUI.getBusinessLogic()
References gui.MainGUI.facade.
Referenced by gui.QueryAvailabilityGUI.jbInit, gui.QueryAvailabilityClientAdvacedGUI.jbInit, gui.SetAvailabilityGUI.jButton1_actionPerformed, gui.QueryAvailabilityGUI.jButton1_actionPerformed, gui.MainGUI.MainGUI, gui.OwnerGUI.OwnerGUI.
static void gui.MainGUI.setBussinessLogic(ApplicationFacadeInterfaceWS afi)
References gui.MainGUI.facade.
Referenced by gui.ApplicationLauncher.main.
gui.MainGUI.MainGUI()
This is the default constructor.
References gui.MainGUI.facade, gui.MainGUI.getBusinessLogic, gui.MainGUI.initialize.
void gui.MainGUI.initialize()
This method initializes this.
void
References gui.MainGUI.getJContentPane.
Referenced by gui.MainGUI.MainGUI.
JPanel gui.MainGUI.getJContentPane()
This method initializes jContentPane.
javax.swing.JPanel
References gui.MainGUI.getBoton3, gui.MainGUI.getLblLogedInAs, gui.MainGUI.getLblNewLabel, gui.MainGUI.getLblType, gui.MainGUI.getPanel, gui.MainGUI.jContentPane.
Referenced by gui.MainGUI.initialize.
JButton gui.MainGUI.getBoton3()
This method initializes boton3.
javax.swing.JButton
References gui.MainGUI.boton3.
Referenced by gui.MainGUI.getJContentPane.
JLabel gui.MainGUI.getLblNewLabel()
References gui.MainGUI.lblNewLabel.
Referenced by gui.MainGUI.getJContentPane.
JRadioButton gui.MainGUI.getRdbtnNewRadioButton()
References gui.MainGUI.buttonGroup, gui.MainGUI.rdbtnNewRadioButton, gui.MainGUI.redibujar.
Referenced by gui.MainGUI.getPanel.
JRadioButton gui.MainGUI.getRdbtnNewRadioButton_1()
References gui.MainGUI.buttonGroup, gui.MainGUI.rdbtnNewRadioButton_1, gui.MainGUI.redibujar.
Referenced by gui.MainGUI.getPanel.
JRadioButton gui.MainGUI.getRdbtnNewRadioButton_2()
References gui.MainGUI.buttonGroup, gui.MainGUI.rdbtnNewRadioButton_2, gui.MainGUI.redibujar.
Referenced by gui.MainGUI.getPanel.
JPanel gui.MainGUI.getPanel()
References gui.MainGUI.getRdbtnNewRadioButton, gui.MainGUI.getRdbtnNewRadioButton_1, gui.MainGUI.getRdbtnNewRadioButton_2, gui.MainGUI.panel.
Referenced by gui.MainGUI.getJContentPane.
void gui.MainGUI.redibujar()
References gui.MainGUI.boton3, gui.MainGUI.lblNewLabel.
Referenced by gui.MainGUI.getRdbtnNewRadioButton, gui.MainGUI.getRdbtnNewRadioButton_1, gui.MainGUI.getRdbtnNewRadioButton_2.
JLabel gui.MainGUI.getLblLogedInAs()
References gui.MainGUI.lblLogedInAs.
Referenced by gui.MainGUI.getJContentPane.
JLabel gui.MainGUI.getLblType()
References gui.MainGUI.lblType.
Referenced by gui.MainGUI.getJContentPane.
Owner gui.MainGUI.getMainOwner()
References gui.MainGUI.facade, businessLogic.ApplicationFacadeInterfaceWS.getOwnerByUsername, domain.Owner.getUserName, gui.MainGUI.owner.
Referenced by gui.ModifyHouseGUI.ModifyHouseGUI, gui.OwnerGUI.OwnerGUI, gui.SetHouse.SetHouse.