dataAccess::DataAccess
String dataAccess.DataAccess.fileName
EntityManagerFactory dataAccess.DataAccess.emf
Referenced by dataAccess.DataAccess.DataAccess.
EntityManager dataAccess.DataAccess.db
Referenced by dataAccess.DataAccess.addImageToRH, dataAccess.DataAccess.close, dataAccess.DataAccess.createClient, dataAccess.DataAccess.createFeedBack, dataAccess.DataAccess.createOffer, dataAccess.DataAccess.createOwner, dataAccess.DataAccess.createReserva, dataAccess.DataAccess.createRuralHouse, dataAccess.DataAccess.DataAccess, dataAccess.DataAccess.existsOverlappingOffer, dataAccess.DataAccess.getAllRuralHouses, dataAccess.DataAccess.getClientByUsername, dataAccess.DataAccess.getImagesFromRH, dataAccess.DataAccess.getOfferByNum, dataAccess.DataAccess.getOffers, dataAccess.DataAccess.getOwnerByUsername, dataAccess.DataAccess.getReservaByNum, dataAccess.DataAccess.getRuralHouse, dataAccess.DataAccess.getRuralHouseByHouseNumber, dataAccess.DataAccess.remove2, dataAccess.DataAccess.removeReserva, dataAccess.DataAccess.removeRuralHouse, dataAccess.DataAccess.setRated, dataAccess.DataAccess.updateClient, dataAccess.DataAccess.updateClinetValidation, dataAccess.DataAccess.updateOwner, dataAccess.DataAccess.updateOwnerValidation.
ConfigXML dataAccess.DataAccess.c
Referenced by dataAccess.DataAccess.createReserva, dataAccess.DataAccess.DataAccess, dataAccess.DataAccess.removeReserva, dataAccess.DataAccess.updateClient, dataAccess.DataAccess.updateClinetValidation.
boolean dataAccess.DataAccess.debuger
Referenced by dataAccess.DataAccess.addImageToRH, dataAccess.DataAccess.createClient, dataAccess.DataAccess.createOwner, dataAccess.DataAccess.createRuralHouse, dataAccess.DataAccess.getClientByUsername, dataAccess.DataAccess.getImagesFromRH, dataAccess.DataAccess.getRuralHouse.
dataAccess.DataAccess.DataAccess()
References dataAccess.DataAccess.c, dataAccess.DataAccess.db, dataAccess.DataAccess.emf, configuration.ConfigXML.getDatabaseNode, configuration.ConfigXML.getDatabasePort, configuration.ConfigXML.getDbFilename, configuration.ConfigXML.getInstance, configuration.ConfigXML.getPassword, configuration.ConfigXML.getUser, configuration.ConfigXML.isDatabaseLocal.
Client dataAccess.DataAccess.createClient(String username, String password, String telegramId, String cuentaBancaria, String email)
Crea un cliente en la base de datos.
String username String password OverlappingClientExists
References dataAccess.DataAccess.db, dataAccess.DataAccess.debuger, dataAccess.DataAccess.existClient, domain.Client.toString.
Referenced by businessLogic.FacadeImplementationWS.createClient.
Owner dataAccess.DataAccess.createOwner(String username, String password, String telegramId, String cuentaBancaria, String email)
Crea un propietario en la base de datos.
String username String password OverlappingOwnerExist
References dataAccess.DataAccess.db, dataAccess.DataAccess.debuger, dataAccess.DataAccess.existOwner, domain.Owner.toString.
Referenced by businessLogic.FacadeImplementationWS.createOwner.
Reserva dataAccess.DataAccess.createReserva(Offer offer, Client cliente, Date bookDate)
References dataAccess.DataAccess.c, dataAccess.DataAccess.db, dataAccess.DataAccess.getClientByUsername, dataAccess.DataAccess.getOfferByNum, domain.Offer.getOfferNumber, domain.Client.getUserName.
Referenced by businessLogic.FacadeImplementationWS.createReserva.
RuralHouse dataAccess.DataAccess.createRuralHouse(Owner o, String city, String description, String address, String roomsNumber)
Crea una casa rural en la base de datos y actualiza la lista de casas del propietario con esta casa.
String city String description Owner o
References domain.Owner.addRhList, dataAccess.DataAccess.db, dataAccess.DataAccess.debuger, dataAccess.DataAccess.getOwnerByUsername, domain.Owner.getUserName, domain.Owner.toString.
Referenced by businessLogic.FacadeImplementationWS.createRuralHouse.
Offer dataAccess.DataAccess.createOffer(RuralHouse ruralHouse, Date firstDay, Date lastDay, float price)
References domain.RuralHouse.createOffer, dataAccess.DataAccess.db, domain.RuralHouse.getHouseNumber.
Referenced by businessLogic.FacadeImplementationWS.createOffer.
void dataAccess.DataAccess.addImageToRH(byte[] img, RuralHouse rh, Owner owner)
References domain.RuralHouse.addImage, dataAccess.DataAccess.db, dataAccess.DataAccess.debuger, dataAccess.DataAccess.getRuralHouse, domain.RuralHouse.toString.
Referenced by businessLogic.FacadeImplementationWS.addImageToRH.
Reserva dataAccess.DataAccess.getReservaByNum(int n)
References dataAccess.DataAccess.db.
Referenced by businessLogic.FacadeImplementationWS.getReservaByNum, dataAccess.DataAccess.removeReserva.
void dataAccess.DataAccess.removeReserva(Reserva r)
References dataAccess.DataAccess.c, dataAccess.DataAccess.db, domain.Reserva.getCliente, domain.Reserva.getNumResrva, domain.Reserva.getOffer, dataAccess.DataAccess.getReservaByNum, domain.Offer.removeReserva.
Referenced by businessLogic.FacadeImplementationWS.removeReserva.
Offer dataAccess.DataAccess.getOfferByNum(int n)
References dataAccess.DataAccess.db.
Referenced by dataAccess.DataAccess.createReserva.
Vector<byte[]> dataAccess.DataAccess.getImagesFromRH(RuralHouse rh, Owner owner)
References dataAccess.DataAccess.db, dataAccess.DataAccess.debuger, domain.RuralHouse.getHouseNumber.
RuralHouse dataAccess.DataAccess.getRuralHouse(Owner owner, RuralHouse rh)
References dataAccess.DataAccess.db, dataAccess.DataAccess.debuger, domain.RuralHouse.getHouseNumber, domain.RuralHouse.toString.
Referenced by dataAccess.DataAccess.addImageToRH, businessLogic.FacadeImplementationWS.getRuralHouse.
Vector<RuralHouse> dataAccess.DataAccess.getAllRuralHouses()
References dataAccess.DataAccess.db.
Referenced by businessLogic.FacadeImplementationWS.getAllRuralHouses.
Vector<Offer> dataAccess.DataAccess.getOffers(RuralHouse rh, Date firstDay, Date lastDay)
References dataAccess.DataAccess.db, domain.RuralHouse.getHouseNumber, domain.RuralHouse.getOffers.
Referenced by businessLogic.FacadeImplementationWS.getOffers.
Client dataAccess.DataAccess.getClientByUsername(String username)
devuelve un cliente dado su "username"
String Client
References dataAccess.DataAccess.db, dataAccess.DataAccess.debuger, domain.Client.toString.
Referenced by dataAccess.DataAccess.createReserva, dataAccess.DataAccess.existClient, businessLogic.FacadeImplementationWS.getClientByUsername.
Owner dataAccess.DataAccess.getOwnerByUsername(String username)
username
References dataAccess.DataAccess.db, domain.Owner.toString.
Referenced by dataAccess.DataAccess.createRuralHouse, dataAccess.DataAccess.existOwner, businessLogic.FacadeImplementationWS.getOwnerByUsername.
boolean dataAccess.DataAccess.existsOverlappingOffer(RuralHouse rh, Date firstDay, Date lastDay)
References dataAccess.DataAccess.db, domain.RuralHouse.getHouseNumber, domain.RuralHouse.overlapsWith.
Referenced by businessLogic.FacadeImplementationWS.createOffer.
boolean dataAccess.DataAccess.existClient(String username)
References dataAccess.DataAccess.getClientByUsername.
Referenced by dataAccess.DataAccess.createClient.
boolean dataAccess.DataAccess.existOwner(String username)
References dataAccess.DataAccess.getOwnerByUsername.
Referenced by dataAccess.DataAccess.createOwner.
RuralHouse dataAccess.DataAccess.getRuralHouseByHouseNumber(int num)
References dataAccess.DataAccess.db.
Referenced by businessLogic.FacadeImplementationWS.getRuralHousebyHouseNumber.
void dataAccess.DataAccess.removeRuralHouse(int num)
References dataAccess.DataAccess.db, domain.RuralHouse.getOwner, domain.Owner.removeRuralHouse.
Referenced by businessLogic.FacadeImplementationWS.removeRuralHouse.
void dataAccess.DataAccess.close()
References dataAccess.DataAccess.db.
Referenced by businessLogic.FacadeImplementationWS.addImageToRH, businessLogic.FacadeImplementationWS.close, businessLogic.FacadeImplementationWS.createClient, businessLogic.FacadeImplementationWS.createFeedBack, businessLogic.FacadeImplementationWS.createOffer, businessLogic.FacadeImplementationWS.createOwner, businessLogic.FacadeImplementationWS.createReserva, businessLogic.FacadeImplementationWS.createRuralHouse, businessLogic.FacadeImplementationWS.getAllRuralHouses, businessLogic.FacadeImplementationWS.getClientByUsername, businessLogic.FacadeImplementationWS.getOffers, businessLogic.FacadeImplementationWS.getOwnerByUsername, businessLogic.FacadeImplementationWS.getReservaByNum, businessLogic.FacadeImplementationWS.getRuralHouse, businessLogic.FacadeImplementationWS.getRuralHousebyHouseNumber, businessLogic.FacadeImplementationWS.removeReserva, businessLogic.FacadeImplementationWS.removeRuralHouse, businessLogic.FacadeImplementationWS.setRated, businessLogic.FacadeImplementationWS.updateClient, businessLogic.FacadeImplementationWS.updateOwner.
void dataAccess.DataAccess.updateClinetValidation(Client c)
References dataAccess.DataAccess.c, dataAccess.DataAccess.db, domain.Client.setValidated.
Referenced by businessLogic.FacadeImplementationWS.updateClinetValidation.
void dataAccess.DataAccess.updateOwnerValidation(Owner o)
References dataAccess.DataAccess.db, domain.Owner.getUserName, domain.Owner.setValidated.
Referenced by businessLogic.FacadeImplementationWS.updateOwnerValidation.
void dataAccess.DataAccess.remove2(RuralHouse rh)
References dataAccess.DataAccess.db.
Client dataAccess.DataAccess.updateClient(Client c)
References dataAccess.DataAccess.c, dataAccess.DataAccess.db, configuration.ConfigXML.getPassword, domain.Client.setCuentaBancaria, domain.Client.setEmail, domain.Client.setPassword, domain.Client.setSendBookByEmail, domain.Client.setSendBookByTelegram, domain.Client.setTelegramId.
Referenced by businessLogic.FacadeImplementationWS.updateClient.
Owner dataAccess.DataAccess.updateOwner(Owner o)
References dataAccess.DataAccess.db, domain.Owner.getCuentaBancaria, domain.Owner.getEmail, domain.Owner.getPassword, domain.Owner.getTelegramId, domain.Owner.getUserName, domain.Owner.isSendBookByTelegram, domain.Owner.setCuentaBancaria, domain.Owner.setEmail, domain.Owner.setPassword, domain.Owner.setSendBookByTelegram, domain.Owner.setTelegramId.
Referenced by businessLogic.FacadeImplementationWS.updateOwner.
FeedBack dataAccess.DataAccess.createFeedBack(int i, String s, RuralHouse rh)
References domain.RuralHouse.addFeedBack, dataAccess.DataAccess.db, domain.RuralHouse.getHouseNumber.
Referenced by businessLogic.FacadeImplementationWS.createFeedBack.
void dataAccess.DataAccess.setRated(Reserva r)
References dataAccess.DataAccess.db, domain.Reserva.getNumResrva, domain.Reserva.setRated.
Referenced by businessLogic.FacadeImplementationWS.setRated.