gui::ClientMainGUI
final long gui.ClientMainGUI.serialVersionUID
ApplicationFacadeInterfaceWS gui.ClientMainGUI.appFacadeInterface
Referenced by gui.ClientMainGUI.getBusinessLogic, gui.ClientMainGUI.setBussinessLogic.
JPanel gui.ClientMainGUI.jContentPane
Referenced by gui.ClientMainGUI.getJContentPane.
JButton gui.ClientMainGUI.boton1
JButton gui.ClientMainGUI.boton3
Referenced by gui.ClientMainGUI.getBoton3, gui.ClientMainGUI.redibujar.
final ButtonGroup gui.ClientMainGUI.buttonGroup
JButton gui.ClientMainGUI.btnLogOut
Referenced by gui.ClientMainGUI.getBtnLogOut.
JLabel gui.ClientMainGUI.lblNewLabel
Referenced by gui.ClientMainGUI.getLblNewLabel, gui.ClientMainGUI.redibujar.
static ApplicationFacadeInterfaceWS gui.ClientMainGUI.getBusinessLogic()
References gui.ClientMainGUI.appFacadeInterface.
Referenced by gui.ClientMainGUI.ClientMainGUI.
static void gui.ClientMainGUI.setBussinessLogic(ApplicationFacadeInterfaceWS afi)
References gui.ClientMainGUI.appFacadeInterface.
gui.ClientMainGUI.ClientMainGUI()
This is the default constructor.
References gui.ClientMainGUI.getBusinessLogic, gui.ClientMainGUI.initialize.
JPanel gui.ClientMainGUI.getJContentPane()
This method initializes jContentPane.
javax.swing.JPanel
References gui.ClientMainGUI.getBoton3, gui.ClientMainGUI.getBtnLogOut, gui.ClientMainGUI.getLblNewLabel, gui.ClientMainGUI.jContentPane.
Referenced by gui.ClientMainGUI.initialize.
void gui.ClientMainGUI.initialize()
This method initializes this.
void
References gui.ClientMainGUI.getJContentPane.
Referenced by gui.ClientMainGUI.ClientMainGUI.
JButton gui.ClientMainGUI.getBoton3()
This method initializes boton3.
javax.swing.JButton
References gui.ClientMainGUI.boton3.
Referenced by gui.ClientMainGUI.getJContentPane.
JLabel gui.ClientMainGUI.getLblNewLabel()
References gui.ClientMainGUI.lblNewLabel.
Referenced by gui.ClientMainGUI.getJContentPane.
void gui.ClientMainGUI.redibujar()
References gui.ClientMainGUI.boton3, gui.ClientMainGUI.lblNewLabel.
JButton gui.ClientMainGUI.getBtnLogOut()
References gui.ClientMainGUI.btnLogOut, gui.MainGUI.client.
Referenced by gui.ClientMainGUI.getJContentPane.