domain::Reserva
Offer domain.Reserva.offer
Referenced by domain.Reserva.getOffer, domain.Reserva.Reserva, domain.Reserva.setOffer, domain.Reserva.toString2.
Integer domain.Reserva.numResrva
Referenced by domain.Reserva.getNumResrva, domain.Reserva.setNumResrva.
Client domain.Reserva.cliente
Referenced by domain.Reserva.getCliente, domain.Reserva.Reserva, domain.Reserva.setCliente.
Date domain.Reserva.bookDate
Referenced by domain.Reserva.getBookDate, domain.Reserva.Reserva, domain.Reserva.setBookDate.
boolean domain.Reserva.isRated
Referenced by gui.MisReservasGUI.MisReservasGUI.
domain.Reserva.Reserva(Offer offer, Client cliente, Date bookDate)
References domain.Reserva.bookDate, domain.Reserva.cliente, domain.Reserva.isRated, domain.Reserva.offer.
domain.Reserva.Reserva()
Offer domain.Reserva.getOffer()
References domain.Reserva.offer.
Referenced by gui.FeedBackGUI.FeedBackGUI, dataAccess.DataAccess.removeReserva, domain.ReservaOfferRhOwnerContainer.ReservaOfferRhOwnerContainer.
boolean domain.Reserva.isRated()
Referenced by domain.Reserva.Reserva, domain.Reserva.setRated.
void domain.Reserva.setRated(boolean isRated)
References domain.Reserva.isRated.
Referenced by dataAccess.DataAccess.setRated.
void domain.Reserva.setOffer(Offer offer)
References domain.Reserva.offer.
int domain.Reserva.getNumResrva()
References domain.Reserva.numResrva.
Referenced by businessLogic.FacadeImplementationWS.getListReservaOfferRhOwnerContainer, businessLogic.FacadeImplementationWS.getReservaOfferRhOwnerContainer, dataAccess.DataAccess.removeReserva, businessLogic.SendBooking.sendBookToTelegram, dataAccess.DataAccess.setRated.
void domain.Reserva.setNumResrva(int numResrva)
References domain.Reserva.numResrva.
Client domain.Reserva.getCliente()
References domain.Reserva.cliente.
Referenced by dataAccess.DataAccess.removeReserva.
void domain.Reserva.setCliente(Client cliente)
References domain.Reserva.cliente.
Date domain.Reserva.getBookDate()
References domain.Reserva.bookDate.
void domain.Reserva.setBookDate(Date bookDate)
References domain.Reserva.bookDate.
String domain.Reserva.toString2()
References domain.RuralHouse.getAddress, domain.RuralHouse.getCity, domain.Offer.getFirstDay, domain.Offer.getLastDay, domain.Offer.getRuralHouse, domain.Reserva.offer.
Referenced by gui.QueryAvailabilityClientAdvacedGUI.jButton1_actionPerformed, businessLogic.SendBooking.sendBookToTelegram.