domain::Owner
String domain.Owner.userName
Referenced by domain.Owner.getUserName, domain.Owner.Owner, domain.Owner.setUserName.
String domain.Owner.password
Referenced by domain.Owner.getPassword, domain.Owner.Owner, domain.Owner.setPassword.
ArrayList<RuralHouse> domain.Owner.rhList
Referenced by domain.Owner.getRhList, domain.Owner.getRhListAsVector, domain.Owner.Owner, domain.Owner.removeRuralHouse, domain.Owner.toString.
String domain.Owner.telegramId
Referenced by domain.Owner.getTelegramId, domain.Owner.Owner, domain.Owner.setTelegramId.
String domain.Owner.cuentaBancaria
Referenced by domain.Owner.getCuentaBancaria, domain.Owner.Owner, domain.Owner.setCuentaBancaria.
String domain.Owner.email
Referenced by domain.Owner.getEmail, domain.Owner.Owner, domain.Owner.setEmail.
int domain.Owner.validationNumber
Referenced by domain.Owner.getValidationNumber, domain.Owner.Owner, domain.Owner.setValidationNumber.
boolean domain.Owner.validated
Referenced by domain.Owner.isValidated, domain.Owner.Owner, domain.Owner.setValidated.
boolean domain.Owner.sendBookByTelegram
Referenced by domain.Owner.isSendBookByTelegram, domain.Owner.Owner, domain.Owner.setSendBookByTelegram.
domain.Owner.Owner()
domain.Owner.Owner(String userName, String password, String telegramId, String cuentaBancaria, String email)
References domain.Owner.cuentaBancaria, domain.Owner.email, businessLogic.GenerateValidationCode.getValidationNumber, domain.Owner.password, domain.Owner.rhList, domain.Owner.sendBookByTelegram, domain.Owner.telegramId, domain.Owner.userName, domain.Owner.validated, domain.Owner.validationNumber.
boolean domain.Owner.isSendBookByTelegram()
References domain.Owner.sendBookByTelegram.
Referenced by gui.QueryAvailabilityClientAdvacedGUI.jButton1_actionPerformed, gui.ModifyAccountGUI.ModifyAccountGUI, dataAccess.DataAccess.updateOwner, gui.ModifyAccountGUI.updateTxtFields.
void domain.Owner.setSendBookByTelegram(boolean sendBookByTelegram)
References domain.Owner.sendBookByTelegram.
Referenced by gui.ModifyAccountGUI.ModifyAccountGUI, dataAccess.DataAccess.updateOwner.
boolean domain.Owner.isValidated()
References domain.Owner.validated.
Referenced by gui.LoginGUI.LoginGUI.
void domain.Owner.setValidated(boolean validated)
References domain.Owner.validated.
Referenced by dataAccess.DataAccess.updateOwnerValidation.
String domain.Owner.getTelegramId()
References domain.Owner.telegramId.
Referenced by gui.ModifyAccountGUI.ModifyAccountGUI, businessLogic.SendBooking.sendBookToTelegram, dataAccess.DataAccess.updateOwner, gui.ModifyAccountGUI.updateTxtFields, gui.ValidationGUI.ValidationGUI.
void domain.Owner.setTelegramId(String telegramId)
References domain.Owner.telegramId.
Referenced by gui.ModifyAccountGUI.ModifyAccountGUI, dataAccess.DataAccess.updateOwner.
String domain.Owner.getCuentaBancaria()
References domain.Owner.cuentaBancaria.
Referenced by gui.ModifyAccountGUI.ModifyAccountGUI, dataAccess.DataAccess.updateOwner, gui.ModifyAccountGUI.updateTxtFields.
void domain.Owner.setCuentaBancaria(String cuentaBancaria)
References domain.Owner.cuentaBancaria.
Referenced by gui.ModifyAccountGUI.ModifyAccountGUI, dataAccess.DataAccess.updateOwner.
String domain.Owner.getEmail()
References domain.Owner.email.
Referenced by gui.QueryAvailabilityClientAdvacedGUI.jButton1_actionPerformed, gui.ModifyAccountGUI.ModifyAccountGUI, dataAccess.DataAccess.updateOwner, gui.ModifyAccountGUI.updateTxtFields, gui.ValidationGUI.ValidationGUI.
void domain.Owner.setEmail(String email)
References domain.Owner.email.
Referenced by gui.ModifyAccountGUI.ModifyAccountGUI, dataAccess.DataAccess.updateOwner.
int domain.Owner.getValidationNumber()
References domain.Owner.validationNumber.
Referenced by gui.ValidationGUI.ValidationGUI.
void domain.Owner.setValidationNumber(int validationNumber)
References domain.Owner.validationNumber.
Vector<RuralHouse> domain.Owner.getRhListAsVector()
References domain.Owner.rhList.
ArrayList<RuralHouse> domain.Owner.getRhList()
References domain.Owner.rhList.
Referenced by gui.ModifyHouseGUI.ModifyHouseGUI, gui.OwnerGUI.OwnerGUI.
void domain.Owner.addRhList(RuralHouse rh)
Referenced by dataAccess.DataAccess.createRuralHouse, gui.SetHouse.SetHouse.
String domain.Owner.getUserName()
References domain.Owner.userName.
Referenced by dataAccess.DataAccess.createRuralHouse, gui.MainGUI.getMainOwner, gui.SetAvailabilityGUI.jbInit, gui.QueryAvailabilityClientAdvacedGUI.jButton1_actionPerformed, gui.ModifyAccountGUI.ModifyAccountGUI, dataAccess.DataAccess.updateOwner, dataAccess.DataAccess.updateOwnerValidation, gui.ModifyAccountGUI.updateTxtFields, gui.ValidationGUI.ValidationGUI.
void domain.Owner.setUserName(String userName)
References domain.Owner.userName.
String domain.Owner.getPassword()
References domain.Owner.password.
Referenced by businessLogic.Login.doLogin, gui.ModifyAccountGUI.ModifyAccountGUI, dataAccess.DataAccess.updateOwner, gui.ModifyAccountGUI.updateTxtFields.
void domain.Owner.setPassword(String password)
References domain.Owner.password.
Referenced by gui.ModifyAccountGUI.ModifyAccountGUI, dataAccess.DataAccess.updateOwner.
void domain.Owner.removeRuralHouse(RuralHouse rh)
References domain.Owner.rhList.
Referenced by dataAccess.DataAccess.removeRuralHouse.
String domain.Owner.toString()
References domain.Owner.rhList.
Referenced by dataAccess.DataAccess.createOwner, dataAccess.DataAccess.createRuralHouse, dataAccess.DataAccess.getOwnerByUsername, gui.OwnerGUI.OwnerGUI.