businessLogic::ApplicationFacadeInterfaceWS
Reserva businessLogic.ApplicationFacadeInterfaceWS.createReserva(Offer offer, Client cliente, Date bookDate, String state)
Referenced by gui.QueryAvailabilityClientAdvacedGUI.jButton1_actionPerformed.
void businessLogic.ApplicationFacadeInterfaceWS.removeReserva(Reserva r)
Referenced by gui.MisReservasGUI.MisReservasGUI.
Offer businessLogic.ApplicationFacadeInterfaceWS.createOffer(RuralHouse ruralHouse, Date firstDay, Date lastDay, float price)
Referenced by gui.SetAvailabilityGUI.jButton1_actionPerformed.
Client businessLogic.ApplicationFacadeInterfaceWS.createClient(String userName, String password, String telegramId, String cuentaBancaria, String email)
Referenced by gui.SignIn.SignIn.
Owner businessLogic.ApplicationFacadeInterfaceWS.createOwner(String userName, String password, String telegramId, String cuentaBancaria, String email)
Referenced by gui.SignIn.SignIn.
void businessLogic.ApplicationFacadeInterfaceWS.updateClinetValidation(Client c)
Referenced by gui.ValidationGUI.ValidationGUI.
void businessLogic.ApplicationFacadeInterfaceWS.updateOwnerValidation(Owner o)
Referenced by gui.ValidationGUI.ValidationGUI.
RuralHouse businessLogic.ApplicationFacadeInterfaceWS.createRuralHouse(Owner o, String city, String description, String address, String roomsNumber)
Referenced by gui.SetHouse.SetHouse.
Vector<RuralHouse> businessLogic.ApplicationFacadeInterfaceWS.getAllRuralHouses()
Referenced by gui.QueryAvailabilityGUI.jbInit, gui.QueryAvailabilityClientAdvacedGUI.jbInit.
Vector<Offer> businessLogic.ApplicationFacadeInterfaceWS.getOffers(RuralHouse rh, Date firstDay, Date lastDay)
Referenced by gui.QueryAvailabilityGUI.jButton1_actionPerformed.
Client businessLogic.ApplicationFacadeInterfaceWS.getClientByUsername(String user)
Referenced by gui.LoginGUI.LoginGUI, gui.MisReservasGUI.MisReservasGUI.
Owner businessLogic.ApplicationFacadeInterfaceWS.getOwnerByUsername(String user)
Referenced by gui.MainGUI.getMainOwner, gui.LoginGUI.LoginGUI.
void businessLogic.ApplicationFacadeInterfaceWS.addImageToRH(byte[] img, Owner owner, RuralHouse rh)
Referenced by gui.ModifyHouseGUI.ModifyHouseGUI.
RuralHouse businessLogic.ApplicationFacadeInterfaceWS.getRuralHouse(RuralHouse rh, Owner owner)
Referenced by gui.ModifyHouseGUI.ModifyHouseGUI.
RuralHouse businessLogic.ApplicationFacadeInterfaceWS.getRuralHousebyHouseNumber(int num)
Referenced by gui.DeleteRuralHouse.DeleteRuralHouse.
void businessLogic.ApplicationFacadeInterfaceWS.removeRuralHouse(int num)
Referenced by gui.DeleteRuralHouse.DeleteRuralHouse.
void businessLogic.ApplicationFacadeInterfaceWS.close()
Reserva businessLogic.ApplicationFacadeInterfaceWS.getReservaByNum(int n)
Referenced by businessLogic.SendBooking.sendBookToTelegram.
ReservaOfferRhOwnerContainer businessLogic.ApplicationFacadeInterfaceWS.getReservaOfferRhOwnerContainer(Reserva r)
Referenced by gui.QueryAvailabilityClientAdvacedGUI.jButton1_actionPerformed.
Client businessLogic.ApplicationFacadeInterfaceWS.updateClient(Client c)
Referenced by gui.ModifyAccountGUI.ModifyAccountGUI.
Owner businessLogic.ApplicationFacadeInterfaceWS.updateOwner(Owner o)
Referenced by gui.ModifyAccountGUI.ModifyAccountGUI.
ArrayList<ReservaOfferRhOwnerContainer> businessLogic.ApplicationFacadeInterfaceWS.getListReservaOfferRhOwnerContainer(Client c)
Referenced by gui.MisReservasGUI.MisReservasGUI.
FeedBack businessLogic.ApplicationFacadeInterfaceWS.createFeedBack(String s, int i, RuralHouse rh)
Referenced by gui.FeedBackGUI.FeedBackGUI.
void businessLogic.ApplicationFacadeInterfaceWS.setRated(Reserva r)
Referenced by gui.FeedBackGUI.FeedBackGUI.